---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: sampleapp
  template:
    metadata:
      labels:
        name: gsampleapp
    spec:
      containers:
      - name: sampleapp
        image: testrepo/sampleapp:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:           
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:         
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1 